// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteActorsInternal.proto

package remote_actors.protobuf;

public final class RemoteActorsInternal {
  private RemoteActorsInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum PBufServiceMode
      implements com.google.protobuf.ProtocolMessageEnum {
    BLOCKING(0, 0),
    NON_BLOCKING(1, 1),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static PBufServiceMode valueOf(int value) {
      switch (value) {
        case 0: return BLOCKING;
        case 1: return NON_BLOCKING;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<PBufServiceMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBufServiceMode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBufServiceMode>() {
            public PBufServiceMode findValueByNumber(int number) {
              return PBufServiceMode.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final PBufServiceMode[] VALUES = {
      BLOCKING, NON_BLOCKING, 
    };
    public static PBufServiceMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private PBufServiceMode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      remote_actors.protobuf.RemoteActorsInternal.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:remote_actors.protobuf.PBufServiceMode)
  }
  
  public static final class PBufNode extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufNode.newBuilder() to construct.
    private PBufNode() {
      initFields();
    }
    private PBufNode(boolean noInit) {}
    
    private static final PBufNode defaultInstance;
    public static PBufNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufNode_fieldAccessorTable;
    }
    
    // required string address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private boolean hasPort;
    private int port_ = 0;
    public boolean hasPort() { return hasPort; }
    public int getPort() { return port_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasAddress) return false;
      if (!hasPort) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAddress()) {
        output.writeString(1, getAddress());
      }
      if (hasPort()) {
        output.writeInt32(2, getPort());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAddress());
      }
      if (hasPort()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getPort());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufNode result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufNode.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufNode();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufNode internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufNode();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufNode getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufNode build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufNode buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufNode returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufNode) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufNode other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAddress(input.readString());
              break;
            }
            case 16: {
              setPort(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string address = 1;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // required int32 port = 2;
      public boolean hasPort() {
        return result.hasPort();
      }
      public int getPort() {
        return result.getPort();
      }
      public Builder setPort(int value) {
        result.hasPort = true;
        result.port_ = value;
        return this;
      }
      public Builder clearPort() {
        result.hasPort = false;
        result.port_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufNode)
    }
    
    static {
      defaultInstance = new PBufNode(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufNode)
  }
  
  public static final class PBufLocator extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufLocator.newBuilder() to construct.
    private PBufLocator() {
      initFields();
    }
    private PBufLocator(boolean noInit) {}
    
    private static final PBufLocator defaultInstance;
    public static PBufLocator getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufLocator getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufLocator_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufLocator_fieldAccessorTable;
    }
    
    // required .remote_actors.protobuf.PBufNode node = 1;
    public static final int NODE_FIELD_NUMBER = 1;
    private boolean hasNode;
    private remote_actors.protobuf.RemoteActorsInternal.PBufNode node_;
    public boolean hasNode() { return hasNode; }
    public remote_actors.protobuf.RemoteActorsInternal.PBufNode getNode() { return node_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
      node_ = remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasNode) return false;
      if (!hasName) return false;
      if (!getNode().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasNode()) {
        output.writeMessage(1, getNode());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasNode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getNode());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufLocator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufLocator result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufLocator.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufLocator();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufLocator internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufLocator();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufLocator getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufLocator build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufLocator buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufLocator buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufLocator returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufLocator) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufLocator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufLocator other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance()) return this;
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              remote_actors.protobuf.RemoteActorsInternal.PBufNode.Builder subBuilder = remote_actors.protobuf.RemoteActorsInternal.PBufNode.newBuilder();
              if (hasNode()) {
                subBuilder.mergeFrom(getNode());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNode(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .remote_actors.protobuf.PBufNode node = 1;
      public boolean hasNode() {
        return result.hasNode();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufNode getNode() {
        return result.getNode();
      }
      public Builder setNode(remote_actors.protobuf.RemoteActorsInternal.PBufNode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNode = true;
        result.node_ = value;
        return this;
      }
      public Builder setNode(remote_actors.protobuf.RemoteActorsInternal.PBufNode.Builder builderForValue) {
        result.hasNode = true;
        result.node_ = builderForValue.build();
        return this;
      }
      public Builder mergeNode(remote_actors.protobuf.RemoteActorsInternal.PBufNode value) {
        if (result.hasNode() &&
            result.node_ != remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance()) {
          result.node_ =
            remote_actors.protobuf.RemoteActorsInternal.PBufNode.newBuilder(result.node_).mergeFrom(value).buildPartial();
        } else {
          result.node_ = value;
        }
        result.hasNode = true;
        return this;
      }
      public Builder clearNode() {
        result.hasNode = false;
        result.node_ = remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance();
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufLocator)
    }
    
    static {
      defaultInstance = new PBufLocator(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufLocator)
  }
  
  public static final class PBufNamedSend extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufNamedSend.newBuilder() to construct.
    private PBufNamedSend() {
      initFields();
    }
    private PBufNamedSend(boolean noInit) {}
    
    private static final PBufNamedSend defaultInstance;
    public static PBufNamedSend getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufNamedSend getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufNamedSend_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufNamedSend_fieldAccessorTable;
    }
    
    // required .remote_actors.protobuf.PBufLocator senderLoc = 1;
    public static final int SENDERLOC_FIELD_NUMBER = 1;
    private boolean hasSenderLoc;
    private remote_actors.protobuf.RemoteActorsInternal.PBufLocator senderLoc_;
    public boolean hasSenderLoc() { return hasSenderLoc; }
    public remote_actors.protobuf.RemoteActorsInternal.PBufLocator getSenderLoc() { return senderLoc_; }
    
    // required .remote_actors.protobuf.PBufLocator receiverLoc = 2;
    public static final int RECEIVERLOC_FIELD_NUMBER = 2;
    private boolean hasReceiverLoc;
    private remote_actors.protobuf.RemoteActorsInternal.PBufLocator receiverLoc_;
    public boolean hasReceiverLoc() { return hasReceiverLoc; }
    public remote_actors.protobuf.RemoteActorsInternal.PBufLocator getReceiverLoc() { return receiverLoc_; }
    
    // optional bytes metaData = 3;
    public static final int METADATA_FIELD_NUMBER = 3;
    private boolean hasMetaData;
    private com.google.protobuf.ByteString metaData_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMetaData() { return hasMetaData; }
    public com.google.protobuf.ByteString getMetaData() { return metaData_; }
    
    // required bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private boolean hasData;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasData() { return hasData; }
    public com.google.protobuf.ByteString getData() { return data_; }
    
    // required string session = 5;
    public static final int SESSION_FIELD_NUMBER = 5;
    private boolean hasSession;
    private java.lang.String session_ = "";
    public boolean hasSession() { return hasSession; }
    public java.lang.String getSession() { return session_; }
    
    private void initFields() {
      senderLoc_ = remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance();
      receiverLoc_ = remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasSenderLoc) return false;
      if (!hasReceiverLoc) return false;
      if (!hasData) return false;
      if (!hasSession) return false;
      if (!getSenderLoc().isInitialized()) return false;
      if (!getReceiverLoc().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSenderLoc()) {
        output.writeMessage(1, getSenderLoc());
      }
      if (hasReceiverLoc()) {
        output.writeMessage(2, getReceiverLoc());
      }
      if (hasMetaData()) {
        output.writeBytes(3, getMetaData());
      }
      if (hasData()) {
        output.writeBytes(4, getData());
      }
      if (hasSession()) {
        output.writeString(5, getSession());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSenderLoc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSenderLoc());
      }
      if (hasReceiverLoc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReceiverLoc());
      }
      if (hasMetaData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMetaData());
      }
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getData());
      }
      if (hasSession()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getSession());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend.getDefaultInstance()) return this;
        if (other.hasSenderLoc()) {
          mergeSenderLoc(other.getSenderLoc());
        }
        if (other.hasReceiverLoc()) {
          mergeReceiverLoc(other.getReceiverLoc());
        }
        if (other.hasMetaData()) {
          setMetaData(other.getMetaData());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasSession()) {
          setSession(other.getSession());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              remote_actors.protobuf.RemoteActorsInternal.PBufLocator.Builder subBuilder = remote_actors.protobuf.RemoteActorsInternal.PBufLocator.newBuilder();
              if (hasSenderLoc()) {
                subBuilder.mergeFrom(getSenderLoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSenderLoc(subBuilder.buildPartial());
              break;
            }
            case 18: {
              remote_actors.protobuf.RemoteActorsInternal.PBufLocator.Builder subBuilder = remote_actors.protobuf.RemoteActorsInternal.PBufLocator.newBuilder();
              if (hasReceiverLoc()) {
                subBuilder.mergeFrom(getReceiverLoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReceiverLoc(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setMetaData(input.readBytes());
              break;
            }
            case 34: {
              setData(input.readBytes());
              break;
            }
            case 42: {
              setSession(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .remote_actors.protobuf.PBufLocator senderLoc = 1;
      public boolean hasSenderLoc() {
        return result.hasSenderLoc();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufLocator getSenderLoc() {
        return result.getSenderLoc();
      }
      public Builder setSenderLoc(remote_actors.protobuf.RemoteActorsInternal.PBufLocator value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSenderLoc = true;
        result.senderLoc_ = value;
        return this;
      }
      public Builder setSenderLoc(remote_actors.protobuf.RemoteActorsInternal.PBufLocator.Builder builderForValue) {
        result.hasSenderLoc = true;
        result.senderLoc_ = builderForValue.build();
        return this;
      }
      public Builder mergeSenderLoc(remote_actors.protobuf.RemoteActorsInternal.PBufLocator value) {
        if (result.hasSenderLoc() &&
            result.senderLoc_ != remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance()) {
          result.senderLoc_ =
            remote_actors.protobuf.RemoteActorsInternal.PBufLocator.newBuilder(result.senderLoc_).mergeFrom(value).buildPartial();
        } else {
          result.senderLoc_ = value;
        }
        result.hasSenderLoc = true;
        return this;
      }
      public Builder clearSenderLoc() {
        result.hasSenderLoc = false;
        result.senderLoc_ = remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance();
        return this;
      }
      
      // required .remote_actors.protobuf.PBufLocator receiverLoc = 2;
      public boolean hasReceiverLoc() {
        return result.hasReceiverLoc();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufLocator getReceiverLoc() {
        return result.getReceiverLoc();
      }
      public Builder setReceiverLoc(remote_actors.protobuf.RemoteActorsInternal.PBufLocator value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasReceiverLoc = true;
        result.receiverLoc_ = value;
        return this;
      }
      public Builder setReceiverLoc(remote_actors.protobuf.RemoteActorsInternal.PBufLocator.Builder builderForValue) {
        result.hasReceiverLoc = true;
        result.receiverLoc_ = builderForValue.build();
        return this;
      }
      public Builder mergeReceiverLoc(remote_actors.protobuf.RemoteActorsInternal.PBufLocator value) {
        if (result.hasReceiverLoc() &&
            result.receiverLoc_ != remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance()) {
          result.receiverLoc_ =
            remote_actors.protobuf.RemoteActorsInternal.PBufLocator.newBuilder(result.receiverLoc_).mergeFrom(value).buildPartial();
        } else {
          result.receiverLoc_ = value;
        }
        result.hasReceiverLoc = true;
        return this;
      }
      public Builder clearReceiverLoc() {
        result.hasReceiverLoc = false;
        result.receiverLoc_ = remote_actors.protobuf.RemoteActorsInternal.PBufLocator.getDefaultInstance();
        return this;
      }
      
      // optional bytes metaData = 3;
      public boolean hasMetaData() {
        return result.hasMetaData();
      }
      public com.google.protobuf.ByteString getMetaData() {
        return result.getMetaData();
      }
      public Builder setMetaData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMetaData = true;
        result.metaData_ = value;
        return this;
      }
      public Builder clearMetaData() {
        result.hasMetaData = false;
        result.metaData_ = getDefaultInstance().getMetaData();
        return this;
      }
      
      // required bytes data = 4;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.protobuf.ByteString getData() {
        return result.getData();
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // required string session = 5;
      public boolean hasSession() {
        return result.hasSession();
      }
      public java.lang.String getSession() {
        return result.getSession();
      }
      public Builder setSession(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSession = true;
        result.session_ = value;
        return this;
      }
      public Builder clearSession() {
        result.hasSession = false;
        result.session_ = getDefaultInstance().getSession();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufNamedSend)
    }
    
    static {
      defaultInstance = new PBufNamedSend(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufNamedSend)
  }
  
  public static final class PBufProxy extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufProxy.newBuilder() to construct.
    private PBufProxy() {
      initFields();
    }
    private PBufProxy(boolean noInit) {}
    
    private static final PBufProxy defaultInstance;
    public static PBufProxy getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufProxy getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufProxy_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufProxy_fieldAccessorTable;
    }
    
    // required .remote_actors.protobuf.PBufNode remoteNode = 1;
    public static final int REMOTENODE_FIELD_NUMBER = 1;
    private boolean hasRemoteNode;
    private remote_actors.protobuf.RemoteActorsInternal.PBufNode remoteNode_;
    public boolean hasRemoteNode() { return hasRemoteNode; }
    public remote_actors.protobuf.RemoteActorsInternal.PBufNode getRemoteNode() { return remoteNode_; }
    
    // required .remote_actors.protobuf.PBufServiceMode mode = 2;
    public static final int MODE_FIELD_NUMBER = 2;
    private boolean hasMode;
    private remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode mode_;
    public boolean hasMode() { return hasMode; }
    public remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode getMode() { return mode_; }
    
    // required string serializerClassName = 3;
    public static final int SERIALIZERCLASSNAME_FIELD_NUMBER = 3;
    private boolean hasSerializerClassName;
    private java.lang.String serializerClassName_ = "";
    public boolean hasSerializerClassName() { return hasSerializerClassName; }
    public java.lang.String getSerializerClassName() { return serializerClassName_; }
    
    // required string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
      remoteNode_ = remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance();
      mode_ = remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode.BLOCKING;
    }
    public final boolean isInitialized() {
      if (!hasRemoteNode) return false;
      if (!hasMode) return false;
      if (!hasSerializerClassName) return false;
      if (!hasName) return false;
      if (!getRemoteNode().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRemoteNode()) {
        output.writeMessage(1, getRemoteNode());
      }
      if (hasMode()) {
        output.writeEnum(2, getMode().getNumber());
      }
      if (hasSerializerClassName()) {
        output.writeString(3, getSerializerClassName());
      }
      if (hasName()) {
        output.writeString(4, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRemoteNode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRemoteNode());
      }
      if (hasMode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getMode().getNumber());
      }
      if (hasSerializerClassName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSerializerClassName());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufProxy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufProxy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufProxy result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufProxy.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufProxy();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufProxy internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufProxy();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufProxy.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufProxy getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufProxy.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufProxy build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufProxy buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufProxy buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufProxy returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufProxy) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufProxy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufProxy other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufProxy.getDefaultInstance()) return this;
        if (other.hasRemoteNode()) {
          mergeRemoteNode(other.getRemoteNode());
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasSerializerClassName()) {
          setSerializerClassName(other.getSerializerClassName());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              remote_actors.protobuf.RemoteActorsInternal.PBufNode.Builder subBuilder = remote_actors.protobuf.RemoteActorsInternal.PBufNode.newBuilder();
              if (hasRemoteNode()) {
                subBuilder.mergeFrom(getRemoteNode());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRemoteNode(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode value = remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setMode(value);
              }
              break;
            }
            case 26: {
              setSerializerClassName(input.readString());
              break;
            }
            case 34: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .remote_actors.protobuf.PBufNode remoteNode = 1;
      public boolean hasRemoteNode() {
        return result.hasRemoteNode();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufNode getRemoteNode() {
        return result.getRemoteNode();
      }
      public Builder setRemoteNode(remote_actors.protobuf.RemoteActorsInternal.PBufNode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRemoteNode = true;
        result.remoteNode_ = value;
        return this;
      }
      public Builder setRemoteNode(remote_actors.protobuf.RemoteActorsInternal.PBufNode.Builder builderForValue) {
        result.hasRemoteNode = true;
        result.remoteNode_ = builderForValue.build();
        return this;
      }
      public Builder mergeRemoteNode(remote_actors.protobuf.RemoteActorsInternal.PBufNode value) {
        if (result.hasRemoteNode() &&
            result.remoteNode_ != remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance()) {
          result.remoteNode_ =
            remote_actors.protobuf.RemoteActorsInternal.PBufNode.newBuilder(result.remoteNode_).mergeFrom(value).buildPartial();
        } else {
          result.remoteNode_ = value;
        }
        result.hasRemoteNode = true;
        return this;
      }
      public Builder clearRemoteNode() {
        result.hasRemoteNode = false;
        result.remoteNode_ = remote_actors.protobuf.RemoteActorsInternal.PBufNode.getDefaultInstance();
        return this;
      }
      
      // required .remote_actors.protobuf.PBufServiceMode mode = 2;
      public boolean hasMode() {
        return result.hasMode();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode getMode() {
        return result.getMode();
      }
      public Builder setMode(remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMode = true;
        result.mode_ = value;
        return this;
      }
      public Builder clearMode() {
        result.hasMode = false;
        result.mode_ = remote_actors.protobuf.RemoteActorsInternal.PBufServiceMode.BLOCKING;
        return this;
      }
      
      // required string serializerClassName = 3;
      public boolean hasSerializerClassName() {
        return result.hasSerializerClassName();
      }
      public java.lang.String getSerializerClassName() {
        return result.getSerializerClassName();
      }
      public Builder setSerializerClassName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSerializerClassName = true;
        result.serializerClassName_ = value;
        return this;
      }
      public Builder clearSerializerClassName() {
        result.hasSerializerClassName = false;
        result.serializerClassName_ = getDefaultInstance().getSerializerClassName();
        return this;
      }
      
      // required string name = 4;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufProxy)
    }
    
    static {
      defaultInstance = new PBufProxy(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufProxy)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufLocator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufLocator_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufNamedSend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufNamedSend_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufProxy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufProxy_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032RemoteActorsInternal.proto\022\026remote_act" +
      "ors.protobuf\")\n\010PBufNode\022\017\n\007address\030\001 \002(" +
      "\t\022\014\n\004port\030\002 \002(\005\"K\n\013PBufLocator\022.\n\004node\030\001" +
      " \002(\0132 .remote_actors.protobuf.PBufNode\022\014" +
      "\n\004name\030\002 \002(\t\"\262\001\n\rPBufNamedSend\0226\n\tsender" +
      "Loc\030\001 \002(\0132#.remote_actors.protobuf.PBufL" +
      "ocator\0228\n\013receiverLoc\030\002 \002(\0132#.remote_act" +
      "ors.protobuf.PBufLocator\022\020\n\010metaData\030\003 \001" +
      "(\014\022\014\n\004data\030\004 \002(\014\022\017\n\007session\030\005 \002(\t\"\243\001\n\tPB" +
      "ufProxy\0224\n\nremoteNode\030\001 \002(\0132 .remote_act",
      "ors.protobuf.PBufNode\0225\n\004mode\030\002 \002(\0162\'.re" +
      "mote_actors.protobuf.PBufServiceMode\022\033\n\023" +
      "serializerClassName\030\003 \002(\t\022\014\n\004name\030\004 \002(\t*" +
      "1\n\017PBufServiceMode\022\014\n\010BLOCKING\020\000\022\020\n\014NON_" +
      "BLOCKING\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_remote_actors_protobuf_PBufNode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_remote_actors_protobuf_PBufNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufNode_descriptor,
              new java.lang.String[] { "Address", "Port", },
              remote_actors.protobuf.RemoteActorsInternal.PBufNode.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufNode.Builder.class);
          internal_static_remote_actors_protobuf_PBufLocator_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_remote_actors_protobuf_PBufLocator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufLocator_descriptor,
              new java.lang.String[] { "Node", "Name", },
              remote_actors.protobuf.RemoteActorsInternal.PBufLocator.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufLocator.Builder.class);
          internal_static_remote_actors_protobuf_PBufNamedSend_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_remote_actors_protobuf_PBufNamedSend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufNamedSend_descriptor,
              new java.lang.String[] { "SenderLoc", "ReceiverLoc", "MetaData", "Data", "Session", },
              remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufNamedSend.Builder.class);
          internal_static_remote_actors_protobuf_PBufProxy_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_remote_actors_protobuf_PBufProxy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufProxy_descriptor,
              new java.lang.String[] { "RemoteNode", "Mode", "SerializerClassName", "Name", },
              remote_actors.protobuf.RemoteActorsInternal.PBufProxy.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufProxy.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
