// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/RemoteActorsInternal.proto

package remote_actors.protobuf;

public final class RemoteActorsInternal {
  private RemoteActorsInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PBufSend extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufSend.newBuilder() to construct.
    private PBufSend() {
      initFields();
    }
    private PBufSend(boolean noInit) {}
    
    private static final PBufSend defaultInstance;
    public static PBufSend getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufSend getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufSend_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufSend_fieldAccessorTable;
    }
    
    public enum PBufSendType
        implements com.google.protobuf.ProtocolMessageEnum {
      ASYNC_SEND(0, 1),
      SYNC_SEND(1, 2),
      SYNC_REPLY(2, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static PBufSendType valueOf(int value) {
        switch (value) {
          case 1: return ASYNC_SEND;
          case 2: return SYNC_SEND;
          case 3: return SYNC_REPLY;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<PBufSendType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PBufSendType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PBufSendType>() {
              public PBufSendType findValueByNumber(int number) {
                return PBufSendType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufSend.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PBufSendType[] VALUES = {
        ASYNC_SEND, SYNC_SEND, SYNC_REPLY, 
      };
      public static PBufSendType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private PBufSendType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        remote_actors.protobuf.RemoteActorsInternal.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:remote_actors.protobuf.PBufSend.PBufSendType)
    }
    
    // required .remote_actors.protobuf.PBufSend.PBufSendType sendType = 1;
    public static final int SENDTYPE_FIELD_NUMBER = 1;
    private boolean hasSendType;
    private remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType sendType_;
    public boolean hasSendType() { return hasSendType; }
    public remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType getSendType() { return sendType_; }
    
    // optional string senderName = 2;
    public static final int SENDERNAME_FIELD_NUMBER = 2;
    private boolean hasSenderName;
    private java.lang.String senderName_ = "";
    public boolean hasSenderName() { return hasSenderName; }
    public java.lang.String getSenderName() { return senderName_; }
    
    // required string receiverName = 3;
    public static final int RECEIVERNAME_FIELD_NUMBER = 3;
    private boolean hasReceiverName;
    private java.lang.String receiverName_ = "";
    public boolean hasReceiverName() { return hasReceiverName; }
    public java.lang.String getReceiverName() { return receiverName_; }
    
    // optional bytes metaData = 4;
    public static final int METADATA_FIELD_NUMBER = 4;
    private boolean hasMetaData;
    private com.google.protobuf.ByteString metaData_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMetaData() { return hasMetaData; }
    public com.google.protobuf.ByteString getMetaData() { return metaData_; }
    
    // required bytes data = 5;
    public static final int DATA_FIELD_NUMBER = 5;
    private boolean hasData;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasData() { return hasData; }
    public com.google.protobuf.ByteString getData() { return data_; }
    
    // optional string session = 6;
    public static final int SESSION_FIELD_NUMBER = 6;
    private boolean hasSession;
    private java.lang.String session_ = "";
    public boolean hasSession() { return hasSession; }
    public java.lang.String getSession() { return session_; }
    
    private void initFields() {
      sendType_ = remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType.ASYNC_SEND;
    }
    public final boolean isInitialized() {
      if (!hasSendType) return false;
      if (!hasReceiverName) return false;
      if (!hasData) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSendType()) {
        output.writeEnum(1, getSendType().getNumber());
      }
      if (hasSenderName()) {
        output.writeString(2, getSenderName());
      }
      if (hasReceiverName()) {
        output.writeString(3, getReceiverName());
      }
      if (hasMetaData()) {
        output.writeBytes(4, getMetaData());
      }
      if (hasData()) {
        output.writeBytes(5, getData());
      }
      if (hasSession()) {
        output.writeString(6, getSession());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSendType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getSendType().getNumber());
      }
      if (hasSenderName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSenderName());
      }
      if (hasReceiverName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getReceiverName());
      }
      if (hasMetaData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMetaData());
      }
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getData());
      }
      if (hasSession()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getSession());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufSend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufSend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufSend result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufSend.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufSend();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufSend internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufSend();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufSend.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufSend getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufSend.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufSend build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufSend buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufSend buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufSend returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufSend) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufSend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufSend other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufSend.getDefaultInstance()) return this;
        if (other.hasSendType()) {
          setSendType(other.getSendType());
        }
        if (other.hasSenderName()) {
          setSenderName(other.getSenderName());
        }
        if (other.hasReceiverName()) {
          setReceiverName(other.getReceiverName());
        }
        if (other.hasMetaData()) {
          setMetaData(other.getMetaData());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasSession()) {
          setSession(other.getSession());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType value = remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setSendType(value);
              }
              break;
            }
            case 18: {
              setSenderName(input.readString());
              break;
            }
            case 26: {
              setReceiverName(input.readString());
              break;
            }
            case 34: {
              setMetaData(input.readBytes());
              break;
            }
            case 42: {
              setData(input.readBytes());
              break;
            }
            case 50: {
              setSession(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .remote_actors.protobuf.PBufSend.PBufSendType sendType = 1;
      public boolean hasSendType() {
        return result.hasSendType();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType getSendType() {
        return result.getSendType();
      }
      public Builder setSendType(remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSendType = true;
        result.sendType_ = value;
        return this;
      }
      public Builder clearSendType() {
        result.hasSendType = false;
        result.sendType_ = remote_actors.protobuf.RemoteActorsInternal.PBufSend.PBufSendType.ASYNC_SEND;
        return this;
      }
      
      // optional string senderName = 2;
      public boolean hasSenderName() {
        return result.hasSenderName();
      }
      public java.lang.String getSenderName() {
        return result.getSenderName();
      }
      public Builder setSenderName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSenderName = true;
        result.senderName_ = value;
        return this;
      }
      public Builder clearSenderName() {
        result.hasSenderName = false;
        result.senderName_ = getDefaultInstance().getSenderName();
        return this;
      }
      
      // required string receiverName = 3;
      public boolean hasReceiverName() {
        return result.hasReceiverName();
      }
      public java.lang.String getReceiverName() {
        return result.getReceiverName();
      }
      public Builder setReceiverName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReceiverName = true;
        result.receiverName_ = value;
        return this;
      }
      public Builder clearReceiverName() {
        result.hasReceiverName = false;
        result.receiverName_ = getDefaultInstance().getReceiverName();
        return this;
      }
      
      // optional bytes metaData = 4;
      public boolean hasMetaData() {
        return result.hasMetaData();
      }
      public com.google.protobuf.ByteString getMetaData() {
        return result.getMetaData();
      }
      public Builder setMetaData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMetaData = true;
        result.metaData_ = value;
        return this;
      }
      public Builder clearMetaData() {
        result.hasMetaData = false;
        result.metaData_ = getDefaultInstance().getMetaData();
        return this;
      }
      
      // required bytes data = 5;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.protobuf.ByteString getData() {
        return result.getData();
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // optional string session = 6;
      public boolean hasSession() {
        return result.hasSession();
      }
      public java.lang.String getSession() {
        return result.getSession();
      }
      public Builder setSession(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSession = true;
        result.session_ = value;
        return this;
      }
      public Builder clearSession() {
        result.hasSession = false;
        result.session_ = getDefaultInstance().getSession();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufSend)
    }
    
    static {
      defaultInstance = new PBufSend(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufSend)
  }
  
  public static final class PBufRemoteApply extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufRemoteApply.newBuilder() to construct.
    private PBufRemoteApply() {
      initFields();
    }
    private PBufRemoteApply(boolean noInit) {}
    
    private static final PBufRemoteApply defaultInstance;
    public static PBufRemoteApply getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufRemoteApply getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufRemoteApply_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufRemoteApply_fieldAccessorTable;
    }
    
    public enum PBufRemoteFunctionType
        implements com.google.protobuf.ProtocolMessageEnum {
      LINK_FUN(0, 1),
      UNLINK_FUN(1, 2),
      EXIT_FUN(2, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static PBufRemoteFunctionType valueOf(int value) {
        switch (value) {
          case 1: return LINK_FUN;
          case 2: return UNLINK_FUN;
          case 3: return EXIT_FUN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<PBufRemoteFunctionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PBufRemoteFunctionType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PBufRemoteFunctionType>() {
              public PBufRemoteFunctionType findValueByNumber(int number) {
                return PBufRemoteFunctionType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PBufRemoteFunctionType[] VALUES = {
        LINK_FUN, UNLINK_FUN, EXIT_FUN, 
      };
      public static PBufRemoteFunctionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private PBufRemoteFunctionType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        remote_actors.protobuf.RemoteActorsInternal.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:remote_actors.protobuf.PBufRemoteApply.PBufRemoteFunctionType)
    }
    
    // required string senderName = 1;
    public static final int SENDERNAME_FIELD_NUMBER = 1;
    private boolean hasSenderName;
    private java.lang.String senderName_ = "";
    public boolean hasSenderName() { return hasSenderName; }
    public java.lang.String getSenderName() { return senderName_; }
    
    // required string receiverName = 2;
    public static final int RECEIVERNAME_FIELD_NUMBER = 2;
    private boolean hasReceiverName;
    private java.lang.String receiverName_ = "";
    public boolean hasReceiverName() { return hasReceiverName; }
    public java.lang.String getReceiverName() { return receiverName_; }
    
    // required .remote_actors.protobuf.PBufRemoteApply.PBufRemoteFunctionType functionType = 3;
    public static final int FUNCTIONTYPE_FIELD_NUMBER = 3;
    private boolean hasFunctionType;
    private remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType functionType_;
    public boolean hasFunctionType() { return hasFunctionType; }
    public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType getFunctionType() { return functionType_; }
    
    // optional string reason = 4;
    public static final int REASON_FIELD_NUMBER = 4;
    private boolean hasReason;
    private java.lang.String reason_ = "";
    public boolean hasReason() { return hasReason; }
    public java.lang.String getReason() { return reason_; }
    
    private void initFields() {
      functionType_ = remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType.LINK_FUN;
    }
    public final boolean isInitialized() {
      if (!hasSenderName) return false;
      if (!hasReceiverName) return false;
      if (!hasFunctionType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSenderName()) {
        output.writeString(1, getSenderName());
      }
      if (hasReceiverName()) {
        output.writeString(2, getReceiverName());
      }
      if (hasFunctionType()) {
        output.writeEnum(3, getFunctionType().getNumber());
      }
      if (hasReason()) {
        output.writeString(4, getReason());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSenderName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSenderName());
      }
      if (hasReceiverName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getReceiverName());
      }
      if (hasFunctionType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, getFunctionType().getNumber());
      }
      if (hasReason()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getReason());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.getDefaultInstance()) return this;
        if (other.hasSenderName()) {
          setSenderName(other.getSenderName());
        }
        if (other.hasReceiverName()) {
          setReceiverName(other.getReceiverName());
        }
        if (other.hasFunctionType()) {
          setFunctionType(other.getFunctionType());
        }
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setSenderName(input.readString());
              break;
            }
            case 18: {
              setReceiverName(input.readString());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType value = remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                setFunctionType(value);
              }
              break;
            }
            case 34: {
              setReason(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string senderName = 1;
      public boolean hasSenderName() {
        return result.hasSenderName();
      }
      public java.lang.String getSenderName() {
        return result.getSenderName();
      }
      public Builder setSenderName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSenderName = true;
        result.senderName_ = value;
        return this;
      }
      public Builder clearSenderName() {
        result.hasSenderName = false;
        result.senderName_ = getDefaultInstance().getSenderName();
        return this;
      }
      
      // required string receiverName = 2;
      public boolean hasReceiverName() {
        return result.hasReceiverName();
      }
      public java.lang.String getReceiverName() {
        return result.getReceiverName();
      }
      public Builder setReceiverName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReceiverName = true;
        result.receiverName_ = value;
        return this;
      }
      public Builder clearReceiverName() {
        result.hasReceiverName = false;
        result.receiverName_ = getDefaultInstance().getReceiverName();
        return this;
      }
      
      // required .remote_actors.protobuf.PBufRemoteApply.PBufRemoteFunctionType functionType = 3;
      public boolean hasFunctionType() {
        return result.hasFunctionType();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType getFunctionType() {
        return result.getFunctionType();
      }
      public Builder setFunctionType(remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFunctionType = true;
        result.functionType_ = value;
        return this;
      }
      public Builder clearFunctionType() {
        result.hasFunctionType = false;
        result.functionType_ = remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.PBufRemoteFunctionType.LINK_FUN;
        return this;
      }
      
      // optional string reason = 4;
      public boolean hasReason() {
        return result.hasReason();
      }
      public java.lang.String getReason() {
        return result.getReason();
      }
      public Builder setReason(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReason = true;
        result.reason_ = value;
        return this;
      }
      public Builder clearReason() {
        result.hasReason = false;
        result.reason_ = getDefaultInstance().getReason();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufRemoteApply)
    }
    
    static {
      defaultInstance = new PBufRemoteApply(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufRemoteApply)
  }
  
  public static final class PBufRemoteStartInvoke extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufRemoteStartInvoke.newBuilder() to construct.
    private PBufRemoteStartInvoke() {
      initFields();
    }
    private PBufRemoteStartInvoke(boolean noInit) {}
    
    private static final PBufRemoteStartInvoke defaultInstance;
    public static PBufRemoteStartInvoke getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufRemoteStartInvoke getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufRemoteStartInvoke_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufRemoteStartInvoke_fieldAccessorTable;
    }
    
    // required string actorClass = 1;
    public static final int ACTORCLASS_FIELD_NUMBER = 1;
    private boolean hasActorClass;
    private java.lang.String actorClass_ = "";
    public boolean hasActorClass() { return hasActorClass; }
    public java.lang.String getActorClass() { return actorClass_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasActorClass) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasActorClass()) {
        output.writeString(1, getActorClass());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasActorClass()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getActorClass());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke.getDefaultInstance()) return this;
        if (other.hasActorClass()) {
          setActorClass(other.getActorClass());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setActorClass(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string actorClass = 1;
      public boolean hasActorClass() {
        return result.hasActorClass();
      }
      public java.lang.String getActorClass() {
        return result.getActorClass();
      }
      public Builder setActorClass(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasActorClass = true;
        result.actorClass_ = value;
        return this;
      }
      public Builder clearActorClass() {
        result.hasActorClass = false;
        result.actorClass_ = getDefaultInstance().getActorClass();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufRemoteStartInvoke)
    }
    
    static {
      defaultInstance = new PBufRemoteStartInvoke(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufRemoteStartInvoke)
  }
  
  public static final class PBufRemoteStartInvokeAndListen extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufRemoteStartInvokeAndListen.newBuilder() to construct.
    private PBufRemoteStartInvokeAndListen() {
      initFields();
    }
    private PBufRemoteStartInvokeAndListen(boolean noInit) {}
    
    private static final PBufRemoteStartInvokeAndListen defaultInstance;
    public static PBufRemoteStartInvokeAndListen getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufRemoteStartInvokeAndListen getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufRemoteStartInvokeAndListen_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.RemoteActorsInternal.internal_static_remote_actors_protobuf_PBufRemoteStartInvokeAndListen_fieldAccessorTable;
    }
    
    // required string actorClass = 1;
    public static final int ACTORCLASS_FIELD_NUMBER = 1;
    private boolean hasActorClass;
    private java.lang.String actorClass_ = "";
    public boolean hasActorClass() { return hasActorClass; }
    public java.lang.String getActorClass() { return actorClass_; }
    
    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private boolean hasPort;
    private int port_ = 0;
    public boolean hasPort() { return hasPort; }
    public int getPort() { return port_; }
    
    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasActorClass) return false;
      if (!hasPort) return false;
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasActorClass()) {
        output.writeString(1, getActorClass());
      }
      if (hasPort()) {
        output.writeInt32(2, getPort());
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasActorClass()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getActorClass());
      }
      if (hasPort()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getPort());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen result;
      
      // Construct using remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen();
        return builder;
      }
      
      protected remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen.getDescriptor();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen getDefaultInstanceForType() {
        return remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen) {
          return mergeFrom((remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen other) {
        if (other == remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen.getDefaultInstance()) return this;
        if (other.hasActorClass()) {
          setActorClass(other.getActorClass());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setActorClass(input.readString());
              break;
            }
            case 16: {
              setPort(input.readInt32());
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string actorClass = 1;
      public boolean hasActorClass() {
        return result.hasActorClass();
      }
      public java.lang.String getActorClass() {
        return result.getActorClass();
      }
      public Builder setActorClass(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasActorClass = true;
        result.actorClass_ = value;
        return this;
      }
      public Builder clearActorClass() {
        result.hasActorClass = false;
        result.actorClass_ = getDefaultInstance().getActorClass();
        return this;
      }
      
      // required int32 port = 2;
      public boolean hasPort() {
        return result.hasPort();
      }
      public int getPort() {
        return result.getPort();
      }
      public Builder setPort(int value) {
        result.hasPort = true;
        result.port_ = value;
        return this;
      }
      public Builder clearPort() {
        result.hasPort = false;
        result.port_ = 0;
        return this;
      }
      
      // required string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.PBufRemoteStartInvokeAndListen)
    }
    
    static {
      defaultInstance = new PBufRemoteStartInvokeAndListen(true);
      remote_actors.protobuf.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.PBufRemoteStartInvokeAndListen)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufSend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufSend_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufRemoteApply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufRemoteApply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufRemoteStartInvoke_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufRemoteStartInvoke_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_PBufRemoteStartInvokeAndListen_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_PBufRemoteStartInvokeAndListen_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/protobuf/RemoteActorsInternal" +
      ".proto\022\026remote_actors.protobuf\"\345\001\n\010PBufS" +
      "end\022?\n\010sendType\030\001 \002(\0162-.remote_actors.pr" +
      "otobuf.PBufSend.PBufSendType\022\022\n\nsenderNa" +
      "me\030\002 \001(\t\022\024\n\014receiverName\030\003 \002(\t\022\020\n\010metaDa" +
      "ta\030\004 \001(\014\022\014\n\004data\030\005 \002(\014\022\017\n\007session\030\006 \001(\t\"" +
      "=\n\014PBufSendType\022\016\n\nASYNC_SEND\020\001\022\r\n\tSYNC_" +
      "SEND\020\002\022\016\n\nSYNC_REPLY\020\003\"\347\001\n\017PBufRemoteApp" +
      "ly\022\022\n\nsenderName\030\001 \002(\t\022\024\n\014receiverName\030\002" +
      " \002(\t\022T\n\014functionType\030\003 \002(\0162>.remote_acto",
      "rs.protobuf.PBufRemoteApply.PBufRemoteFu" +
      "nctionType\022\016\n\006reason\030\004 \001(\t\"D\n\026PBufRemote" +
      "FunctionType\022\014\n\010LINK_FUN\020\001\022\016\n\nUNLINK_FUN" +
      "\020\002\022\014\n\010EXIT_FUN\020\003\"+\n\025PBufRemoteStartInvok" +
      "e\022\022\n\nactorClass\030\001 \002(\t\"P\n\036PBufRemoteStart" +
      "InvokeAndListen\022\022\n\nactorClass\030\001 \002(\t\022\014\n\004p" +
      "ort\030\002 \002(\005\022\014\n\004name\030\003 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_remote_actors_protobuf_PBufSend_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_remote_actors_protobuf_PBufSend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufSend_descriptor,
              new java.lang.String[] { "SendType", "SenderName", "ReceiverName", "MetaData", "Data", "Session", },
              remote_actors.protobuf.RemoteActorsInternal.PBufSend.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufSend.Builder.class);
          internal_static_remote_actors_protobuf_PBufRemoteApply_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_remote_actors_protobuf_PBufRemoteApply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufRemoteApply_descriptor,
              new java.lang.String[] { "SenderName", "ReceiverName", "FunctionType", "Reason", },
              remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufRemoteApply.Builder.class);
          internal_static_remote_actors_protobuf_PBufRemoteStartInvoke_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_remote_actors_protobuf_PBufRemoteStartInvoke_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufRemoteStartInvoke_descriptor,
              new java.lang.String[] { "ActorClass", },
              remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvoke.Builder.class);
          internal_static_remote_actors_protobuf_PBufRemoteStartInvokeAndListen_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_remote_actors_protobuf_PBufRemoteStartInvokeAndListen_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_PBufRemoteStartInvokeAndListen_descriptor,
              new java.lang.String[] { "ActorClass", "Port", "Name", },
              remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen.class,
              remote_actors.protobuf.RemoteActorsInternal.PBufRemoteStartInvokeAndListen.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
