// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/Example.proto

package remote_actors.protobuf.examples;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PBufExample extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufExample.newBuilder() to construct.
    private PBufExample() {
      initFields();
    }
    private PBufExample(boolean noInit) {}
    
    private static final PBufExample defaultInstance;
    public static PBufExample getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufExample getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote_actors.protobuf.examples.Example.internal_static_remote_actors_protobuf_examples_PBufExample_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote_actors.protobuf.examples.Example.internal_static_remote_actors_protobuf_examples_PBufExample_fieldAccessorTable;
    }
    
    // required int32 i = 1;
    public static final int I_FIELD_NUMBER = 1;
    private boolean hasI;
    private int i_ = 0;
    public boolean hasI() { return hasI; }
    public int getI() { return i_; }
    
    // required string s = 2;
    public static final int S_FIELD_NUMBER = 2;
    private boolean hasS;
    private java.lang.String s_ = "";
    public boolean hasS() { return hasS; }
    public java.lang.String getS() { return s_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasI) return false;
      if (!hasS) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasI()) {
        output.writeInt32(1, getI());
      }
      if (hasS()) {
        output.writeString(2, getS());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasI()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getI());
      }
      if (hasS()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getS());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static remote_actors.protobuf.examples.Example.PBufExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(remote_actors.protobuf.examples.Example.PBufExample prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private remote_actors.protobuf.examples.Example.PBufExample result;
      
      // Construct using remote_actors.protobuf.examples.Example.PBufExample.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new remote_actors.protobuf.examples.Example.PBufExample();
        return builder;
      }
      
      protected remote_actors.protobuf.examples.Example.PBufExample internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new remote_actors.protobuf.examples.Example.PBufExample();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote_actors.protobuf.examples.Example.PBufExample.getDescriptor();
      }
      
      public remote_actors.protobuf.examples.Example.PBufExample getDefaultInstanceForType() {
        return remote_actors.protobuf.examples.Example.PBufExample.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public remote_actors.protobuf.examples.Example.PBufExample build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private remote_actors.protobuf.examples.Example.PBufExample buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public remote_actors.protobuf.examples.Example.PBufExample buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        remote_actors.protobuf.examples.Example.PBufExample returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote_actors.protobuf.examples.Example.PBufExample) {
          return mergeFrom((remote_actors.protobuf.examples.Example.PBufExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(remote_actors.protobuf.examples.Example.PBufExample other) {
        if (other == remote_actors.protobuf.examples.Example.PBufExample.getDefaultInstance()) return this;
        if (other.hasI()) {
          setI(other.getI());
        }
        if (other.hasS()) {
          setS(other.getS());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setI(input.readInt32());
              break;
            }
            case 18: {
              setS(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 i = 1;
      public boolean hasI() {
        return result.hasI();
      }
      public int getI() {
        return result.getI();
      }
      public Builder setI(int value) {
        result.hasI = true;
        result.i_ = value;
        return this;
      }
      public Builder clearI() {
        result.hasI = false;
        result.i_ = 0;
        return this;
      }
      
      // required string s = 2;
      public boolean hasS() {
        return result.hasS();
      }
      public java.lang.String getS() {
        return result.getS();
      }
      public Builder setS(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasS = true;
        result.s_ = value;
        return this;
      }
      public Builder clearS() {
        result.hasS = false;
        result.s_ = getDefaultInstance().getS();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:remote_actors.protobuf.examples.PBufExample)
    }
    
    static {
      defaultInstance = new PBufExample(true);
      remote_actors.protobuf.examples.Example.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:remote_actors.protobuf.examples.PBufExample)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_remote_actors_protobuf_examples_PBufExample_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_remote_actors_protobuf_examples_PBufExample_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/Example.proto\022\037remot" +
      "e_actors.protobuf.examples\"#\n\013PBufExampl" +
      "e\022\t\n\001i\030\001 \002(\005\022\t\n\001s\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_remote_actors_protobuf_examples_PBufExample_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_remote_actors_protobuf_examples_PBufExample_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_remote_actors_protobuf_examples_PBufExample_descriptor,
              new java.lang.String[] { "I", "S", },
              remote_actors.protobuf.examples.Example.PBufExample.class,
              remote_actors.protobuf.examples.Example.PBufExample.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
