// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/RemoteActorsInternal.proto

package gsoc_scala;

public final class RemoteActorsInternal {
  private RemoteActorsInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PBufNode extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufNode.newBuilder() to construct.
    private PBufNode() {
      initFields();
    }
    private PBufNode(boolean noInit) {}
    
    private static final PBufNode defaultInstance;
    public static PBufNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gsoc_scala.RemoteActorsInternal.internal_static_gsoc_scala_PBufNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gsoc_scala.RemoteActorsInternal.internal_static_gsoc_scala_PBufNode_fieldAccessorTable;
    }
    
    // required string address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private boolean hasPort;
    private int port_ = 0;
    public boolean hasPort() { return hasPort; }
    public int getPort() { return port_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasAddress) return false;
      if (!hasPort) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAddress()) {
        output.writeString(1, getAddress());
      }
      if (hasPort()) {
        output.writeInt32(2, getPort());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAddress());
      }
      if (hasPort()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getPort());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gsoc_scala.RemoteActorsInternal.PBufNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private gsoc_scala.RemoteActorsInternal.PBufNode result;
      
      // Construct using gsoc_scala.RemoteActorsInternal.PBufNode.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new gsoc_scala.RemoteActorsInternal.PBufNode();
        return builder;
      }
      
      protected gsoc_scala.RemoteActorsInternal.PBufNode internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new gsoc_scala.RemoteActorsInternal.PBufNode();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gsoc_scala.RemoteActorsInternal.PBufNode.getDescriptor();
      }
      
      public gsoc_scala.RemoteActorsInternal.PBufNode getDefaultInstanceForType() {
        return gsoc_scala.RemoteActorsInternal.PBufNode.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public gsoc_scala.RemoteActorsInternal.PBufNode build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private gsoc_scala.RemoteActorsInternal.PBufNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public gsoc_scala.RemoteActorsInternal.PBufNode buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        gsoc_scala.RemoteActorsInternal.PBufNode returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gsoc_scala.RemoteActorsInternal.PBufNode) {
          return mergeFrom((gsoc_scala.RemoteActorsInternal.PBufNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(gsoc_scala.RemoteActorsInternal.PBufNode other) {
        if (other == gsoc_scala.RemoteActorsInternal.PBufNode.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAddress(input.readString());
              break;
            }
            case 16: {
              setPort(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string address = 1;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // required int32 port = 2;
      public boolean hasPort() {
        return result.hasPort();
      }
      public int getPort() {
        return result.getPort();
      }
      public Builder setPort(int value) {
        result.hasPort = true;
        result.port_ = value;
        return this;
      }
      public Builder clearPort() {
        result.hasPort = false;
        result.port_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:gsoc_scala.PBufNode)
    }
    
    static {
      defaultInstance = new PBufNode(true);
      gsoc_scala.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:gsoc_scala.PBufNode)
  }
  
  public static final class PBufLocator extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufLocator.newBuilder() to construct.
    private PBufLocator() {
      initFields();
    }
    private PBufLocator(boolean noInit) {}
    
    private static final PBufLocator defaultInstance;
    public static PBufLocator getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufLocator getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gsoc_scala.RemoteActorsInternal.internal_static_gsoc_scala_PBufLocator_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gsoc_scala.RemoteActorsInternal.internal_static_gsoc_scala_PBufLocator_fieldAccessorTable;
    }
    
    // required .gsoc_scala.PBufNode node = 1;
    public static final int NODE_FIELD_NUMBER = 1;
    private boolean hasNode;
    private gsoc_scala.RemoteActorsInternal.PBufNode node_;
    public boolean hasNode() { return hasNode; }
    public gsoc_scala.RemoteActorsInternal.PBufNode getNode() { return node_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
      node_ = gsoc_scala.RemoteActorsInternal.PBufNode.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasNode) return false;
      if (!hasName) return false;
      if (!getNode().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasNode()) {
        output.writeMessage(1, getNode());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasNode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getNode());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufLocator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gsoc_scala.RemoteActorsInternal.PBufLocator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private gsoc_scala.RemoteActorsInternal.PBufLocator result;
      
      // Construct using gsoc_scala.RemoteActorsInternal.PBufLocator.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new gsoc_scala.RemoteActorsInternal.PBufLocator();
        return builder;
      }
      
      protected gsoc_scala.RemoteActorsInternal.PBufLocator internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new gsoc_scala.RemoteActorsInternal.PBufLocator();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gsoc_scala.RemoteActorsInternal.PBufLocator.getDescriptor();
      }
      
      public gsoc_scala.RemoteActorsInternal.PBufLocator getDefaultInstanceForType() {
        return gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public gsoc_scala.RemoteActorsInternal.PBufLocator build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private gsoc_scala.RemoteActorsInternal.PBufLocator buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public gsoc_scala.RemoteActorsInternal.PBufLocator buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        gsoc_scala.RemoteActorsInternal.PBufLocator returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gsoc_scala.RemoteActorsInternal.PBufLocator) {
          return mergeFrom((gsoc_scala.RemoteActorsInternal.PBufLocator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(gsoc_scala.RemoteActorsInternal.PBufLocator other) {
        if (other == gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance()) return this;
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              gsoc_scala.RemoteActorsInternal.PBufNode.Builder subBuilder = gsoc_scala.RemoteActorsInternal.PBufNode.newBuilder();
              if (hasNode()) {
                subBuilder.mergeFrom(getNode());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNode(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .gsoc_scala.PBufNode node = 1;
      public boolean hasNode() {
        return result.hasNode();
      }
      public gsoc_scala.RemoteActorsInternal.PBufNode getNode() {
        return result.getNode();
      }
      public Builder setNode(gsoc_scala.RemoteActorsInternal.PBufNode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNode = true;
        result.node_ = value;
        return this;
      }
      public Builder setNode(gsoc_scala.RemoteActorsInternal.PBufNode.Builder builderForValue) {
        result.hasNode = true;
        result.node_ = builderForValue.build();
        return this;
      }
      public Builder mergeNode(gsoc_scala.RemoteActorsInternal.PBufNode value) {
        if (result.hasNode() &&
            result.node_ != gsoc_scala.RemoteActorsInternal.PBufNode.getDefaultInstance()) {
          result.node_ =
            gsoc_scala.RemoteActorsInternal.PBufNode.newBuilder(result.node_).mergeFrom(value).buildPartial();
        } else {
          result.node_ = value;
        }
        result.hasNode = true;
        return this;
      }
      public Builder clearNode() {
        result.hasNode = false;
        result.node_ = gsoc_scala.RemoteActorsInternal.PBufNode.getDefaultInstance();
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:gsoc_scala.PBufLocator)
    }
    
    static {
      defaultInstance = new PBufLocator(true);
      gsoc_scala.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:gsoc_scala.PBufLocator)
  }
  
  public static final class PBufNamedSend extends
      com.google.protobuf.GeneratedMessage {
    // Use PBufNamedSend.newBuilder() to construct.
    private PBufNamedSend() {
      initFields();
    }
    private PBufNamedSend(boolean noInit) {}
    
    private static final PBufNamedSend defaultInstance;
    public static PBufNamedSend getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBufNamedSend getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gsoc_scala.RemoteActorsInternal.internal_static_gsoc_scala_PBufNamedSend_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gsoc_scala.RemoteActorsInternal.internal_static_gsoc_scala_PBufNamedSend_fieldAccessorTable;
    }
    
    // required .gsoc_scala.PBufLocator senderLoc = 1;
    public static final int SENDERLOC_FIELD_NUMBER = 1;
    private boolean hasSenderLoc;
    private gsoc_scala.RemoteActorsInternal.PBufLocator senderLoc_;
    public boolean hasSenderLoc() { return hasSenderLoc; }
    public gsoc_scala.RemoteActorsInternal.PBufLocator getSenderLoc() { return senderLoc_; }
    
    // required .gsoc_scala.PBufLocator receiverLoc = 2;
    public static final int RECEIVERLOC_FIELD_NUMBER = 2;
    private boolean hasReceiverLoc;
    private gsoc_scala.RemoteActorsInternal.PBufLocator receiverLoc_;
    public boolean hasReceiverLoc() { return hasReceiverLoc; }
    public gsoc_scala.RemoteActorsInternal.PBufLocator getReceiverLoc() { return receiverLoc_; }
    
    // optional bytes metaData = 3;
    public static final int METADATA_FIELD_NUMBER = 3;
    private boolean hasMetaData;
    private com.google.protobuf.ByteString metaData_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMetaData() { return hasMetaData; }
    public com.google.protobuf.ByteString getMetaData() { return metaData_; }
    
    // required bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private boolean hasData;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasData() { return hasData; }
    public com.google.protobuf.ByteString getData() { return data_; }
    
    // required string session = 5;
    public static final int SESSION_FIELD_NUMBER = 5;
    private boolean hasSession;
    private java.lang.String session_ = "";
    public boolean hasSession() { return hasSession; }
    public java.lang.String getSession() { return session_; }
    
    private void initFields() {
      senderLoc_ = gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance();
      receiverLoc_ = gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasSenderLoc) return false;
      if (!hasReceiverLoc) return false;
      if (!hasData) return false;
      if (!hasSession) return false;
      if (!getSenderLoc().isInitialized()) return false;
      if (!getReceiverLoc().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSenderLoc()) {
        output.writeMessage(1, getSenderLoc());
      }
      if (hasReceiverLoc()) {
        output.writeMessage(2, getReceiverLoc());
      }
      if (hasMetaData()) {
        output.writeBytes(3, getMetaData());
      }
      if (hasData()) {
        output.writeBytes(4, getData());
      }
      if (hasSession()) {
        output.writeString(5, getSession());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSenderLoc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSenderLoc());
      }
      if (hasReceiverLoc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReceiverLoc());
      }
      if (hasMetaData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMetaData());
      }
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getData());
      }
      if (hasSession()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getSession());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gsoc_scala.RemoteActorsInternal.PBufNamedSend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gsoc_scala.RemoteActorsInternal.PBufNamedSend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private gsoc_scala.RemoteActorsInternal.PBufNamedSend result;
      
      // Construct using gsoc_scala.RemoteActorsInternal.PBufNamedSend.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new gsoc_scala.RemoteActorsInternal.PBufNamedSend();
        return builder;
      }
      
      protected gsoc_scala.RemoteActorsInternal.PBufNamedSend internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new gsoc_scala.RemoteActorsInternal.PBufNamedSend();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gsoc_scala.RemoteActorsInternal.PBufNamedSend.getDescriptor();
      }
      
      public gsoc_scala.RemoteActorsInternal.PBufNamedSend getDefaultInstanceForType() {
        return gsoc_scala.RemoteActorsInternal.PBufNamedSend.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public gsoc_scala.RemoteActorsInternal.PBufNamedSend build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private gsoc_scala.RemoteActorsInternal.PBufNamedSend buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public gsoc_scala.RemoteActorsInternal.PBufNamedSend buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        gsoc_scala.RemoteActorsInternal.PBufNamedSend returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gsoc_scala.RemoteActorsInternal.PBufNamedSend) {
          return mergeFrom((gsoc_scala.RemoteActorsInternal.PBufNamedSend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(gsoc_scala.RemoteActorsInternal.PBufNamedSend other) {
        if (other == gsoc_scala.RemoteActorsInternal.PBufNamedSend.getDefaultInstance()) return this;
        if (other.hasSenderLoc()) {
          mergeSenderLoc(other.getSenderLoc());
        }
        if (other.hasReceiverLoc()) {
          mergeReceiverLoc(other.getReceiverLoc());
        }
        if (other.hasMetaData()) {
          setMetaData(other.getMetaData());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasSession()) {
          setSession(other.getSession());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              gsoc_scala.RemoteActorsInternal.PBufLocator.Builder subBuilder = gsoc_scala.RemoteActorsInternal.PBufLocator.newBuilder();
              if (hasSenderLoc()) {
                subBuilder.mergeFrom(getSenderLoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSenderLoc(subBuilder.buildPartial());
              break;
            }
            case 18: {
              gsoc_scala.RemoteActorsInternal.PBufLocator.Builder subBuilder = gsoc_scala.RemoteActorsInternal.PBufLocator.newBuilder();
              if (hasReceiverLoc()) {
                subBuilder.mergeFrom(getReceiverLoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReceiverLoc(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setMetaData(input.readBytes());
              break;
            }
            case 34: {
              setData(input.readBytes());
              break;
            }
            case 42: {
              setSession(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .gsoc_scala.PBufLocator senderLoc = 1;
      public boolean hasSenderLoc() {
        return result.hasSenderLoc();
      }
      public gsoc_scala.RemoteActorsInternal.PBufLocator getSenderLoc() {
        return result.getSenderLoc();
      }
      public Builder setSenderLoc(gsoc_scala.RemoteActorsInternal.PBufLocator value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSenderLoc = true;
        result.senderLoc_ = value;
        return this;
      }
      public Builder setSenderLoc(gsoc_scala.RemoteActorsInternal.PBufLocator.Builder builderForValue) {
        result.hasSenderLoc = true;
        result.senderLoc_ = builderForValue.build();
        return this;
      }
      public Builder mergeSenderLoc(gsoc_scala.RemoteActorsInternal.PBufLocator value) {
        if (result.hasSenderLoc() &&
            result.senderLoc_ != gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance()) {
          result.senderLoc_ =
            gsoc_scala.RemoteActorsInternal.PBufLocator.newBuilder(result.senderLoc_).mergeFrom(value).buildPartial();
        } else {
          result.senderLoc_ = value;
        }
        result.hasSenderLoc = true;
        return this;
      }
      public Builder clearSenderLoc() {
        result.hasSenderLoc = false;
        result.senderLoc_ = gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance();
        return this;
      }
      
      // required .gsoc_scala.PBufLocator receiverLoc = 2;
      public boolean hasReceiverLoc() {
        return result.hasReceiverLoc();
      }
      public gsoc_scala.RemoteActorsInternal.PBufLocator getReceiverLoc() {
        return result.getReceiverLoc();
      }
      public Builder setReceiverLoc(gsoc_scala.RemoteActorsInternal.PBufLocator value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasReceiverLoc = true;
        result.receiverLoc_ = value;
        return this;
      }
      public Builder setReceiverLoc(gsoc_scala.RemoteActorsInternal.PBufLocator.Builder builderForValue) {
        result.hasReceiverLoc = true;
        result.receiverLoc_ = builderForValue.build();
        return this;
      }
      public Builder mergeReceiverLoc(gsoc_scala.RemoteActorsInternal.PBufLocator value) {
        if (result.hasReceiverLoc() &&
            result.receiverLoc_ != gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance()) {
          result.receiverLoc_ =
            gsoc_scala.RemoteActorsInternal.PBufLocator.newBuilder(result.receiverLoc_).mergeFrom(value).buildPartial();
        } else {
          result.receiverLoc_ = value;
        }
        result.hasReceiverLoc = true;
        return this;
      }
      public Builder clearReceiverLoc() {
        result.hasReceiverLoc = false;
        result.receiverLoc_ = gsoc_scala.RemoteActorsInternal.PBufLocator.getDefaultInstance();
        return this;
      }
      
      // optional bytes metaData = 3;
      public boolean hasMetaData() {
        return result.hasMetaData();
      }
      public com.google.protobuf.ByteString getMetaData() {
        return result.getMetaData();
      }
      public Builder setMetaData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMetaData = true;
        result.metaData_ = value;
        return this;
      }
      public Builder clearMetaData() {
        result.hasMetaData = false;
        result.metaData_ = getDefaultInstance().getMetaData();
        return this;
      }
      
      // required bytes data = 4;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.protobuf.ByteString getData() {
        return result.getData();
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // required string session = 5;
      public boolean hasSession() {
        return result.hasSession();
      }
      public java.lang.String getSession() {
        return result.getSession();
      }
      public Builder setSession(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSession = true;
        result.session_ = value;
        return this;
      }
      public Builder clearSession() {
        result.hasSession = false;
        result.session_ = getDefaultInstance().getSession();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:gsoc_scala.PBufNamedSend)
    }
    
    static {
      defaultInstance = new PBufNamedSend(true);
      gsoc_scala.RemoteActorsInternal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:gsoc_scala.PBufNamedSend)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsoc_scala_PBufNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsoc_scala_PBufNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsoc_scala_PBufLocator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsoc_scala_PBufLocator_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsoc_scala_PBufNamedSend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsoc_scala_PBufNamedSend_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/protobuf/RemoteActorsInternal" +
      ".proto\022\tgsoc_scala\")\n\010PBufNode\022\017\n\007address" +
      "\030\001 \002(\t\022\014\n\004port\030\002 \002(\005\">\n\013PBufLocator\022!\n\004n" +
      "ode\030\001 \002(\0132\023.gsoc_scala.PBufNode\022\014\n\004name\030\002" +
      " \002(\t\"\230\001\n\rPBufNamedSend\022)\n\tsenderLoc\030\001 \002(" +
      "\0132\026.gsoc_scala.PBufLocator\022+\n\013receiverLoc" +
      "\030\002 \002(\0132\026.gsoc_scala.PBufLocator\022\020\n\010metaDa" +
      "ta\030\003 \001(\014\022\014\n\004data\030\004 \002(\014\022\017\n\007session\030\005 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gsoc_scala_PBufNode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gsoc_scala_PBufNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsoc_scala_PBufNode_descriptor,
              new java.lang.String[] { "Address", "Port", },
              gsoc_scala.RemoteActorsInternal.PBufNode.class,
              gsoc_scala.RemoteActorsInternal.PBufNode.Builder.class);
          internal_static_gsoc_scala_PBufLocator_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gsoc_scala_PBufLocator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsoc_scala_PBufLocator_descriptor,
              new java.lang.String[] { "Node", "Name", },
              gsoc_scala.RemoteActorsInternal.PBufLocator.class,
              gsoc_scala.RemoteActorsInternal.PBufLocator.Builder.class);
          internal_static_gsoc_scala_PBufNamedSend_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_gsoc_scala_PBufNamedSend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsoc_scala_PBufNamedSend_descriptor,
              new java.lang.String[] { "SenderLoc", "ReceiverLoc", "MetaData", "Data", "Session", },
              gsoc_scala.RemoteActorsInternal.PBufNamedSend.class,
              gsoc_scala.RemoteActorsInternal.PBufNamedSend.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
